/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programas;

import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class Formulario extends javax.swing.JFrame {

    boolean idiomaEspanol,idiomaIngles,idiomaItaliano,idiomaFrances,idiomaJapones,idiomaChino;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
        clsFormulario objFormulario=new clsFormulario();
        
        
        clsIP objIP=new clsIP();
        lblIP.setText("Ip: "+objIP.obtenerIP());        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        ppmMenu = new javax.swing.JPopupMenu();
        pmiNuevo = new javax.swing.JMenuItem();
        pmiGuardar = new javax.swing.JMenuItem();
        pmiEditar = new javax.swing.JMenuItem();
        pmiSalir = new javax.swing.JMenuItem();
        panelVacio = new javax.swing.JPanel();
        Bandera = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        Creador2 = new javax.swing.JLabel();
        creador1 = new javax.swing.JLabel();
        Creado = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        CDestino = new javax.swing.JTextField();
        telefono = new javax.swing.JLabel();
        CTelefono = new javax.swing.JTextField();
        destino = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        Cedad = new javax.swing.JTextField();
        pais = new javax.swing.JLabel();
        ComPais = new javax.swing.JComboBox<>();
        CP = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        Alcaldia = new javax.swing.JLabel();
        CAlcaldia = new javax.swing.JTextField();
        Cnombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Registro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        empresa = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        mniNuevo = new javax.swing.JMenuItem();
        mniGuardar = new javax.swing.JMenuItem();
        mniCancelar = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();
        mnuIdioma = new javax.swing.JMenu();
        mniEspañol = new javax.swing.JMenuItem();
        mniInglés = new javax.swing.JMenuItem();
        spt1 = new javax.swing.JPopupMenu.Separator();
        mniFrancés = new javax.swing.JMenuItem();
        mniItaliano = new javax.swing.JMenuItem();
        spt2 = new javax.swing.JPopupMenu.Separator();
        mniJaponés = new javax.swing.JMenuItem();
        mniChino = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        pmiNuevo.setFont(new java.awt.Font("Forte", 0, 12)); // NOI18N
        pmiNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.jpg"))); // NOI18N
        pmiNuevo.setText("Nuevo");
        pmiNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmiNuevoActionPerformed(evt);
            }
        });
        ppmMenu.add(pmiNuevo);

        pmiGuardar.setFont(new java.awt.Font("Forte", 0, 12)); // NOI18N
        pmiGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GuardarColor.png"))); // NOI18N
        pmiGuardar.setText("Guardar");
        pmiGuardar.setToolTipText("");
        pmiGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmiGuardarActionPerformed(evt);
            }
        });
        ppmMenu.add(pmiGuardar);

        pmiEditar.setFont(new java.awt.Font("Forte", 0, 12)); // NOI18N
        pmiEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.jpg"))); // NOI18N
        pmiEditar.setText("Editar");
        pmiEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmiEditarActionPerformed(evt);
            }
        });
        ppmMenu.add(pmiEditar);

        pmiSalir.setFont(new java.awt.Font("Forte", 0, 12)); // NOI18N
        pmiSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        pmiSalir.setText("Salir");
        pmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmiSalirActionPerformed(evt);
            }
        });
        ppmMenu.add(pmiSalir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de viajes");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 757, 660));
        setMinimumSize(new java.awt.Dimension(757, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        panelVacio.setBackground(new java.awt.Color(255, 255, 255));
        panelVacio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));
        panelVacio.setLayout(null);

        Bandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agencia-viajes.jpg"))); // NOI18N
        panelVacio.add(Bandera);
        Bandera.setBounds(1, 44, 288, 263);

        lblIP.setText("Pais:");
        panelVacio.add(lblIP);
        lblIP.setBounds(11, 12, 220, 16);

        Creador2.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        Creador2.setText("Arizmendi Ponce Jhoana Michel");
        panelVacio.add(Creador2);
        Creador2.setBounds(10, 310, 210, 16);

        creador1.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        creador1.setText("Mejía Castañeda Bryan Emmanuel");
        panelVacio.add(creador1);
        creador1.setBounds(10, 290, 220, 16);

        Creado.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        Creado.setText("Creado por:");
        panelVacio.add(Creado);
        Creado.setBounds(10, 270, 73, 16);

        getContentPane().add(panelVacio);
        panelVacio.setBounds(40, 140, 290, 330);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2));

        nuevo.setBackground(new java.awt.Color(0, 102, 204));
        nuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nuevo.setForeground(new java.awt.Color(255, 255, 255));
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(0, 102, 204));
        guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(0, 102, 204));
        salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(0, 102, 204));
        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(cancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(panelBotones);
        panelBotones.setBounds(40, 490, 660, 66);

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDestinoActionPerformed(evt);
            }
        });

        telefono.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        telefono.setText("Telefono");

        destino.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        destino.setText("Destino");

        nombre.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        nombre.setText("Nombre:");

        edad.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        edad.setText("Edad:");

        Cedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedadActionPerformed(evt);
            }
        });

        pais.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        pais.setText("País:");

        ComPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "México", "Italia", "Japón", "China" }));
        ComPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComPaisActionPerformed(evt);
            }
        });

        CP.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        CP.setText("CP:");

        txtCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPActionPerformed(evt);
            }
        });

        Alcaldia.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        Alcaldia.setText("Alcaldia:");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Cedad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(destino)
                        .addGap(10, 10, 10)
                        .addComponent(CDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDatosLayout.createSequentialGroup()
                            .addComponent(Alcaldia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CAlcaldia, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDatosLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(telefono)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDatosLayout.createSequentialGroup()
                            .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDatosLayout.createSequentialGroup()
                            .addComponent(pais)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ComPais, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cedad))
                .addGap(12, 12, 12)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pais)
                    .addComponent(ComPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alcaldia)
                    .addComponent(CAlcaldia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(CTelefono))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destino))
                .addGap(47, 47, 47))
        );

        getContentPane().add(panelDatos);
        panelDatos.setBounds(350, 140, 350, 330);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2));

        Registro.setFont(new java.awt.Font("Lucida Calligraphy", 0, 36)); // NOI18N
        Registro.setText("Registro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(Registro)
                .addGap(0, 139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(Registro)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 70, 660, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0), 2));

        empresa.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        empresa.setForeground(new java.awt.Color(255, 102, 0));
        empresa.setText("Agencia de viajes Mejía y Arizmendi ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(empresa)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(empresa)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 10, 660, 50);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/madera.jpg"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 740, 610);

        Archivo.setText("Archivo");

        mniNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNuevo.setFont(new java.awt.Font("Forte", 0, 12)); // NOI18N
        mniNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.jpg"))); // NOI18N
        mniNuevo.setText("Nuevo");
        mniNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNuevoActionPerformed(evt);
            }
        });
        Archivo.add(mniNuevo);

        mniGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniGuardar.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        mniGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GuardarColor.png"))); // NOI18N
        mniGuardar.setText("Guardar");
        mniGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGuardarActionPerformed(evt);
            }
        });
        Archivo.add(mniGuardar);

        mniCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniCancelar.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        mniCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cancelar.png"))); // NOI18N
        mniCancelar.setText("Cancelar");
        mniCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCancelarActionPerformed(evt);
            }
        });
        Archivo.add(mniCancelar);

        mniSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSalir.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        mniSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        Archivo.add(mniSalir);

        jMenuBar1.add(Archivo);

        mnuIdioma.setText("Idioma");

        mniEspañol.setText("Español");
        mniEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEspañolActionPerformed(evt);
            }
        });
        mnuIdioma.add(mniEspañol);

        mniInglés.setText("English");
        mniInglés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInglésActionPerformed(evt);
            }
        });
        mnuIdioma.add(mniInglés);
        mnuIdioma.add(spt1);

        mniFrancés.setText("français");
        mniFrancés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFrancésActionPerformed(evt);
            }
        });
        mnuIdioma.add(mniFrancés);

        mniItaliano.setText("Italiano");
        mniItaliano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniItalianoActionPerformed(evt);
            }
        });
        mnuIdioma.add(mniItaliano);
        mnuIdioma.add(spt2);

        mniJaponés.setText("日本人");
        mniJaponés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniJaponésActionPerformed(evt);
            }
        });
        mnuIdioma.add(mniJaponés);

        mniChino.setText("简体中文");
        mniChino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChinoActionPerformed(evt);
            }
        });
        mnuIdioma.add(mniChino);

        jMenuBar1.add(mnuIdioma);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGuardarActionPerformed
        // TODO add your handling code here:
        GuardarDatos();
        LimpiarPantalla();
    }//GEN-LAST:event_mniGuardarActionPerformed

    private void mniNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNuevoActionPerformed
        // TODO add your handling code here:
        Nuevo();
    }//GEN-LAST:event_mniNuevoActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mniSalirActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        Nuevo();
    }//GEN-LAST:event_nuevoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        GuardarDatos();
        LimpiarPantalla();
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void txtCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCPActionPerformed

    private void ComPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComPaisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComPaisActionPerformed

    private void CedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CedadActionPerformed

    private void pmiGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmiGuardarActionPerformed
        // TODO add your handling code here:
        GuardarDatos();
    }//GEN-LAST:event_pmiGuardarActionPerformed

    private void pmiNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmiNuevoActionPerformed
        // TODO add your handling code here:
        LimpiarPantalla();
    }//GEN-LAST:event_pmiNuevoActionPerformed

    private void pmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pmiSalirActionPerformed

    private void pmiEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmiEditarActionPerformed
        // TODO add your handling code here:
        GuardarDatos();
        LimpiarPantalla();
    }//GEN-LAST:event_pmiEditarActionPerformed

    private void mniCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCancelarActionPerformed
        // TODO add your handling code here:
        LimpiarPantalla();
    }//GEN-LAST:event_mniCancelarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        LimpiarPantalla();
    }//GEN-LAST:event_cancelarActionPerformed

    private void mniFrancésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFrancésActionPerformed
        // TODO add your handling code here:
        Registro.setText("Inscription du Client");
        nombre.setText("Nom:");
        edad.setText("Âge:");
        pais.setText("Pays:");
        CP.setText("Code postal:");
        Alcaldia.setText("La mairie:");
        telefono.setText("numéro de téléphone:");
        destino.setText("Destination:");
        nuevo.setText("Nouveau");
        guardar.setText("Sauvegarder");
        cancelar.setText("Annuler");
        salir.setText("Sortir");
        mnuIdioma.setText("langage");
        Archivo.setText("Archiver");
        mniNuevo.setText("Nouveau");
        mniGuardar.setText("Sauvegarder");
        mniCancelar.setText("Annuler");
        mniSalir.setText("Sortir");
        
        idiomaEspanol=false;
        idiomaIngles=false;
        idiomaItaliano=false;
        idiomaFrances=true;
        idiomaJapones=false;
        idiomaChino=false;
    }//GEN-LAST:event_mniFrancésActionPerformed

    private void mniJaponésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniJaponésActionPerformed
        // TODO add your handling code here:
        Registro.setText("クライアント登録");
        nombre.setText("名前：");
        edad.setText("年齢：");
        pais.setText("国：");
        CP.setText("郵便番号：");
        Alcaldia.setText("町役場：");
        telefono.setText("電話番号：");
        destino.setText("先：");
        nuevo.setText("新着");
        guardar.setText("保存する");
        cancelar.setText("キャンセル");
        salir.setText("外出する"); 
        mnuIdioma.setText("言語");
        Archivo.setText("アーカイブ");        
        mniNuevo.setText("新着");
        mniGuardar.setText("保存する");
        mniCancelar.setText("キャンセル");
        mniSalir.setText("外出する");
        
        idiomaEspanol=false;
        idiomaIngles=false;
        idiomaItaliano=false;
        idiomaFrances=false;
        idiomaJapones=true;
        idiomaChino=false;        
    }//GEN-LAST:event_mniJaponésActionPerformed

    private void mniEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEspañolActionPerformed
        // TODO add your handling code here:
        Registro.setText("Registro de Clientes");
        nombre.setText("Nombre:");
        edad.setText("Edad:");
        pais.setText("País:");
        CP.setText("CP:");
        Alcaldia.setText("Alcaldía:");
        telefono.setText("Teléfono:");
        destino.setText("Destino:");
        nuevo.setText("Nuevo");
        guardar.setText("Guardar");
        cancelar.setText("Cancelar");
        salir.setText("Salir");
        mnuIdioma.setText("Idioma");
        Archivo.setText("Archivo");  
        mniNuevo.setText("Nuevo");
        mniGuardar.setText("Guardar");
        mniCancelar.setText("Cancelar");
        mniSalir.setText("Salir");
        
        idiomaEspanol=true;
        idiomaIngles=false;
        idiomaItaliano=false;
        idiomaFrances=false;
        idiomaJapones=false;
        idiomaChino=false;
    }//GEN-LAST:event_mniEspañolActionPerformed

    private void mniInglésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInglésActionPerformed
        // TODO add your handling code here:
        Registro.setText("Customer registration");
        nombre.setText("Full name:");
        edad.setText("Age:");
        pais.setText("Country:");
        CP.setText("Postal Code:");
        Alcaldia.setText("Town hall:");
        telefono.setText("phone number:");
        destino.setText("Destination:");
        nuevo.setText("New");
        guardar.setText("Save");
        cancelar.setText("Cancel");
        salir.setText("Exit"); 
        mnuIdioma.setText("Language");
        Archivo.setText("File");
        mniNuevo.setText("New");
        mniGuardar.setText("Save");
        mniCancelar.setText("Cancel");
        mniSalir.setText("Exit");
        
        idiomaEspanol=false;
        idiomaIngles=true;
        idiomaItaliano=false;
        idiomaFrances=false;
        idiomaJapones=false;
        idiomaChino=false;
    }//GEN-LAST:event_mniInglésActionPerformed

    private void mniItalianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniItalianoActionPerformed
        // TODO add your handling code here:
        Registro.setText("Registrazione del cliente");
        nombre.setText("Nome:");
        edad.setText("Età:");
        pais.setText("Nazione:");
        CP.setText("Codice postale:");
        Alcaldia.setText("Municipio:");
        telefono.setText("numero di telefono:");
        destino.setText("Destinazione:");
        nuevo.setText("Nuovo");
        guardar.setText("Salva");
        cancelar.setText("Annulla");
        salir.setText("Esci");        
        mnuIdioma.setText("linguaggio");
        Archivo.setText("Archivio");   
        mniNuevo.setText("Nuovo");
        mniGuardar.setText("Salva");
        mniCancelar.setText("Annulla");
        mniSalir.setText("Esci");
        
        idiomaEspanol=false;
        idiomaIngles=false;
        idiomaItaliano=true;
        idiomaFrances=false;
        idiomaJapones=false;
        idiomaChino=false;
    }//GEN-LAST:event_mniItalianoActionPerformed

    private void mniChinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChinoActionPerformed
        // TODO add your handling code here:
        Registro.setText("客户注册");
        nombre.setText("名称");
        edad.setText("v年龄");
        pais.setText("国家");
        CP.setText("邮政编码");
        Alcaldia.setText("市政厅");
        telefono.setText("电话号码");
        destino.setText("目的地");
        nuevo.setText("新");
        guardar.setText("保存");
        cancelar.setText("取消");
        salir.setText("出去");
        mnuIdioma.setText("语言");
        Archivo.setText("封存");
        mniNuevo.setText("新");
        mniGuardar.setText("保存");
        mniCancelar.setText("取消");
        mniSalir.setText("出去"); 
        
        idiomaEspanol=false;
        idiomaIngles=false;
        idiomaItaliano=false;
        idiomaFrances=false;
        idiomaJapones=false;
        idiomaChino=true;
    }//GEN-LAST:event_mniChinoActionPerformed

    private void CDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDestinoActionPerformed

    public void LimpiarPantalla(){
        Cnombre.setText("");
        Cedad.setText("");
        ComPais.setSelectedIndex(0);
        txtCP.setText("");
        CTelefono.setText("");
        CDestino.setText("");
        CAlcaldia.setText("");
    }
    
        public void GuardarDatos(){
        String strDatos="";
        String strInfo="";
        
        if(idiomaEspanol=true){
            strInfo="Nombre Edad País de origen Código postal Alcaldía Telefono Destino de vuelo Fecha de vuelo";
        }
        else if(idiomaIngles=true){
            strInfo="Name Age Country of origin Postal Code Town hall Phone number Flight destination Flight date";
        }
        else if(idiomaItaliano=true){
            strInfo="Nome Età paese d'origine Codice postale Municipio numero di telefono Destinazione del volo Data del volo";
        }
        else if(idiomaFrances=true){
            strInfo="Nom Âge Pays d'origine Code postal La mairie Numéro de téléphone Destination du vol Daate du vol";
        }
        else if(idiomaJapones=true){
            strInfo="名前 年齢 原産国 郵便番号 公会堂 電話番号 フライトの目的地 ご搭乗日";
        }
        else if(idiomaChino=true){
            strInfo="名称 v年龄 原产国 邮政编码 大会堂 电话号码 航班目的地 航班日期";
        }
            
            
        strDatos = Cnombre.getText().toString()+" "+Cedad.getText().toString()+" "+ComPais.getSelectedItem().toString()
                +" "+txtCP.getText().toString()+" "+CAlcaldia.getText().toString()+" "+CTelefono.getText().toString()
                +" " +CDestino.getText().toString();
        
        clsFormulario objFormulario=new clsFormulario();
        objFormulario.CrearArchivo(strInfo,strDatos);
        
        Cnombre.setEnabled(false);
        Cedad.setEnabled(false);
        ComPais.setEnabled(false);
        txtCP.setEnabled(false);
        CAlcaldia.setEnabled(false);
        CTelefono.setEnabled(false);
        CDestino.setEnabled(false);
    }
        
    public void Nuevo(){
        Cnombre.setEnabled(true);
        Cedad.setEnabled(true);
        ComPais.setEnabled(true);
        txtCP.setEnabled(true);
        CAlcaldia.setEnabled(true);
        CTelefono.setEnabled(true);
        CDestino.setEnabled(true);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alcaldia;
    private javax.swing.JMenu Archivo;
    private javax.swing.JLabel Bandera;
    private javax.swing.JTextField CAlcaldia;
    private javax.swing.JTextField CDestino;
    private javax.swing.JLabel CP;
    private javax.swing.JTextField CTelefono;
    private javax.swing.JTextField Cedad;
    private javax.swing.JTextField Cnombre;
    private javax.swing.JComboBox<String> ComPais;
    private javax.swing.JLabel Creado;
    private javax.swing.JLabel Creador2;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Registro;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel creador1;
    private javax.swing.JLabel destino;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel empresa;
    private javax.swing.JButton guardar;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIP;
    private javax.swing.JMenuItem mniCancelar;
    private javax.swing.JMenuItem mniChino;
    private javax.swing.JMenuItem mniEspañol;
    private javax.swing.JMenuItem mniFrancés;
    private javax.swing.JMenuItem mniGuardar;
    private javax.swing.JMenuItem mniInglés;
    private javax.swing.JMenuItem mniItaliano;
    private javax.swing.JMenuItem mniJaponés;
    private javax.swing.JMenuItem mniNuevo;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuIdioma;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JLabel pais;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JMenuItem pmiEditar;
    private javax.swing.JMenuItem pmiGuardar;
    private javax.swing.JMenuItem pmiNuevo;
    private javax.swing.JMenuItem pmiSalir;
    private javax.swing.JPopupMenu ppmMenu;
    private javax.swing.JButton salir;
    private javax.swing.JPopupMenu.Separator spt1;
    private javax.swing.JPopupMenu.Separator spt2;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField txtCP;
    // End of variables declaration//GEN-END:variables
}
